name: ci-cd

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-aws-auth:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Run AWS CLI commands
        run: |
          aws sts get-caller-identity
          echo "AWS auth working!"
